"""
Script to generate a mockup ZIP archive demonstrating the output
of the Streamlit Center cookiecutter generator.

This creates a sample project structure that would be generated
when using the visual cookiecutter tool.
"""

import zipfile
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "output"
ZIP_NAME = "my_streamlit_app.zip"
PROJECT_NAME = "my_streamlit_app"


def create_app_py():
    """Main Streamlit app entry point."""
    return '''"""
My Streamlit App - Main Entry Point
Generated by Streamlit Center Cookiecutter
"""

import streamlit as st

st.set_page_config(
    page_title="My Streamlit App",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("📊 My Streamlit App")
st.markdown("---")

st.markdown("""
Welcome to your new Streamlit application!

Use the sidebar to navigate between pages.
""")

# Display project info
with st.expander("ℹ️ Project Information"):
    st.markdown("""
    - **Project Name:** My Streamlit App
    - **Author:** Data Team
    - **Version:** 1.0.0
    """)
'''


def create_page_data_upload():
    """Data upload page."""
    return '''"""
Data Upload Page
"""

import streamlit as st
import pandas as pd

st.title("📤 Data Upload")

uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.dataframe(df)
'''


def create_page_dashboard():
    """Dashboard page."""
    return '''"""
Dashboard Page
"""

import streamlit as st
import pandas as pd

st.title("📈 Dashboard")

# Placeholder metrics
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Total Records", "1,234")
with col2:
    st.metric("Active Users", "56")
with col3:
    st.metric("Success Rate", "94.2%")
'''


def create_page_settings():
    """Settings page."""
    return '''"""
Settings Page
"""

import streamlit as st

st.title("⚙️ Settings")

st.subheader("Application Settings")
theme = st.selectbox("Theme", ["Light", "Dark"])
language = st.selectbox("Language", ["English", "Polish"])

if st.button("Save Settings"):
    st.success("Settings saved!")
'''


def create_requirements():
    """Requirements file."""
    return """streamlit>=1.28.0
pandas>=2.0.0
numpy>=1.24.0
plotly>=5.18.0
"""


def create_readme():
    """README file."""
    return """# My Streamlit App

Generated by **Streamlit Center Cookiecutter**.

## Getting Started

1. Create virtual environment:
   ```bash
   python -m venv venv
   source venv/bin/activate  # Linux/Mac
   venv\\Scripts\\activate   # Windows
   ```

2. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

3. Run the app:
   ```bash
   streamlit run app.py
   ```

## Project Structure

```
my_streamlit_app/
├── app.py                 # Main entry point
├── pg/                    # Multi-page app pages
│   ├── 1_📤_Data_Upload.py
│   ├── 2_📈_Dashboard.py
│   └── 3_⚙️_Settings.py
├── my_streamlit/          # Core application code
│   ├── utils/             # Utility functions
│   │   └── helpers.py
│   └── config/            # Configuration files
│       └── settings.yaml
├── requirements.txt
└── README.md
```

## Support

Contact the BI Data Engineering team for assistance.
"""


def create_helpers():
    """Utility helpers."""
    return '''"""
Utility helper functions
"""

import streamlit as st
from functools import wraps


def log_page_visit(page_name: str):
    """Log page visit for analytics."""
    # Placeholder for logging implementation
    pass


def require_auth(func):
    """Decorator to require authentication."""
    @wraps(func)
    def wrapper(*args, **kwargs):
        if not st.session_state.get("authenticated", False):
            st.error("Please log in to access this page.")
            st.stop()
        return func(*args, **kwargs)
    return wrapper
'''


def create_settings_yaml():
    """Settings configuration."""
    return """# Application Settings
app:
  name: "My Streamlit App"
  version: "1.0.0"
  debug: false

# Database connection (if needed)
database:
  host: "localhost"
  port: 1433
  name: "app_db"

# Logging settings
logging:
  enabled: true
  level: "INFO"
"""


def create_gitignore():
    """Gitignore file."""
    return """# Python
__pycache__/
*.py[cod]
venv/
.env

# IDE
.vscode/
.idea/

# Streamlit
.streamlit/secrets.toml
"""


def generate_archive():
    """Generate the ZIP archive with project structure."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    zip_path = OUTPUT_DIR / ZIP_NAME

    files = {
        f"{PROJECT_NAME}/app.py": create_app_py(),
        f"{PROJECT_NAME}/pg/1_📤_Data_Upload.py": create_page_data_upload(),
        f"{PROJECT_NAME}/pg/2_📈_Dashboard.py": create_page_dashboard(),
        f"{PROJECT_NAME}/pg/3_⚙️_Settings.py": create_page_settings(),
        f"{PROJECT_NAME}/my_streamlit_app/__init__.py": "",
        f"{PROJECT_NAME}/my_streamlit_app/utils/__init__.py": "",
        f"{PROJECT_NAME}/my_streamlit_app/utils/helpers.py": create_helpers(),
        f"{PROJECT_NAME}/my_streamlit_app/config/__init__.py": "",
        f"{PROJECT_NAME}/my_streamlit_app/config/settings.yaml": create_settings_yaml(),
        f"{PROJECT_NAME}/requirements.txt": create_requirements(),
        f"{PROJECT_NAME}/README.md": create_readme(),
        f"{PROJECT_NAME}/.gitignore": create_gitignore(),
    }

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for filepath, content in files.items():
            zf.writestr(filepath, content)

    print(f"✅ Archive generated: {zip_path}")
    print(f"\nContents of {ZIP_NAME}:")
    print("-" * 40)

    with zipfile.ZipFile(zip_path, "r") as zf:
        for name in sorted(zf.namelist()):
            print(f"  {name}")


if __name__ == "__main__":
    generate_archive()
